/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Metadata = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'fileName' : IDL.Text,
  'shareId' : IDL.Text,
  'totalChunks' : IDL.Nat,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChunkIndex = IDL.Nat;
export const Chunk = IDL.Vec(IDL.Nat8);
export const ChunkInfo = IDL.Record({
  'uploadedChunks' : IDL.Nat,
  'totalChunks' : IDL.Nat,
});
export const UploadParams = IDL.Record({
  'title' : IDL.Text,
  'fileName' : IDL.Text,
  'shareId' : IDL.Text,
  'totalChunks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePdf' : IDL.Func([IDL.Text], [], []),
  'finalizeUpload' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'getAllPdfMeta' : IDL.Func([], [IDL.Vec(Metadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPdf' : IDL.Func([IDL.Text], [Metadata], ['query']),
  'getPdfChunk' : IDL.Func([IDL.Text, ChunkIndex], [Chunk], ['query']),
  'getPdfChunks' : IDL.Func([IDL.Text], [ChunkInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startUpload' : IDL.Func([UploadParams], [], []),
  'updatePdfTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadChunk' : IDL.Func([IDL.Text, IDL.Nat, Chunk], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Metadata = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'fileName' : IDL.Text,
    'shareId' : IDL.Text,
    'totalChunks' : IDL.Nat,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChunkIndex = IDL.Nat;
  const Chunk = IDL.Vec(IDL.Nat8);
  const ChunkInfo = IDL.Record({
    'uploadedChunks' : IDL.Nat,
    'totalChunks' : IDL.Nat,
  });
  const UploadParams = IDL.Record({
    'title' : IDL.Text,
    'fileName' : IDL.Text,
    'shareId' : IDL.Text,
    'totalChunks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePdf' : IDL.Func([IDL.Text], [], []),
    'finalizeUpload' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'getAllPdfMeta' : IDL.Func([], [IDL.Vec(Metadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPdf' : IDL.Func([IDL.Text], [Metadata], ['query']),
    'getPdfChunk' : IDL.Func([IDL.Text, ChunkIndex], [Chunk], ['query']),
    'getPdfChunks' : IDL.Func([IDL.Text], [ChunkInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startUpload' : IDL.Func([UploadParams], [], []),
    'updatePdfTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadChunk' : IDL.Func([IDL.Text, IDL.Nat, Chunk], [], []),
  });
};

export const init = ({ IDL }) => { return []; };