/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Chunk = Uint8Array;
export type ChunkIndex = bigint;
export interface ChunkInfo { 'uploadedChunks' : bigint, 'totalChunks' : bigint }
export type ExternalBlob = Uint8Array;
export interface Metadata {
  'title' : string,
  'file' : ExternalBlob,
  'fileName' : string,
  'shareId' : string,
  'totalChunks' : bigint,
  'uploadedAt' : Time,
}
export type Time = bigint;
export interface UploadParams {
  'title' : string,
  'fileName' : string,
  'shareId' : string,
  'totalChunks' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePdf' : ActorMethod<[string], undefined>,
  'finalizeUpload' : ActorMethod<[string, ExternalBlob], undefined>,
  'getAllPdfMeta' : ActorMethod<[], Array<Metadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPdf' : ActorMethod<[string], Metadata>,
  'getPdfChunk' : ActorMethod<[string, ChunkIndex], Chunk>,
  'getPdfChunks' : ActorMethod<[string], ChunkInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startUpload' : ActorMethod<[UploadParams], undefined>,
  'updatePdfTitle' : ActorMethod<[string, string], undefined>,
  'uploadChunk' : ActorMethod<[string, bigint, Chunk], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];